### ISSUE TITLE
Release to Maven Central

### ISSUE THREAD

**Issue by dalifreire** [dalifreire/jerimum#34]
Versionar e publicar o jerimum no repositório central do maven.
Referência de apoio:
- https://maven.apache.org/guides/mini/guide-central-repository-upload.html
- http://central.sonatype.org/pages/requirements.html

**Comment by dalifreire** [comment]
@philipealves Toca o barco...

**Comment by philipealves** [comment]
Done! To deploy, we have to include into the servers tag on Maven settings.xml the OOSRH server configuration (user/pass). After this, just run mvn clean deploy
